Mass shorten links with csv file upload
AmoabaKelvin/ishortn.ink pull request #112
Opened 2024-03-31 19:56 UTC by BreakTos

Demo of csv upload feature

[![Demo Video](https://img.youtube.com/vi/xOzT0hMn208/0.jpg)](https://youtu.be/xOzT0hMn208)

For testing purposes here is a csv file with links column and a few urls in it
[SampleCSVFile_2kb.csv](https://github.com/AmoabaKelvin/ishortn.ink/files/14817473/SampleCSVFile_2kb.csv)

Optional aliases column remains to be implemented. closes #58

2024-03-31 20:29 UTC, AmoabaKelvin requested changes
We can export this to it's own component rather than having everything in the link edit form. The new component will be the button that will be placed on the sidebar and every functionality related to the upload and shortening will be kept in there.

Also, if you can get `prettier` to format the codes, it will be awesome. Please let me know if there is anything else.

2024-03-31 20:29 UTC, AmoabaKelvin commented on src/components/forms/dashboard/links/link-edit-form.tsx
> +            <div className="options" style={{display:"flex",flexDirection:"row",justifyContent:"space-between"}}>
can we replace these styles with tailwindcss classnames
```
<div className="flex justify-between options">
    ...
</div>
```

2024-03-31 20:29 UTC, AmoabaKelvin commented on src/components/forms/dashboard/links/link-edit-form.tsx
> +            }}> Upload CSV</button>
Let's use the `Button` component from the shadcn library we are using so we keep things consistent

2024-04-01 06:03 UTC, BreakTos commented
![image](https://github.com/AmoabaKelvin/ishortn.ink/assets/76687690/c6f167fe-05dd-4853-87ed-e68dd3f838b7)

There we have it, Used prettier and made components to modulate the functionality

2024-04-01 07:41 UTC, AmoabaKelvin requested changes

2024-04-01 07:41 UTC, AmoabaKelvin commented on src/components/forms/dashboard/links/csv-shorten.tsx
> +        style={{ display: "none" }}
you can use the hidden className from tailwindcss here.

```html
<input
    type="file"
    id="inputCSV"
	className="hidden"
    onChange={handleCSV}
></input>
```

2024-04-01 07:41 UTC, AmoabaKelvin commented on src/components/forms/dashboard/links/csv-shorten.tsx
> +  }
We should move the interface outside of the function so it's definition comes before the `CsvShortenForm`

2024-04-01 07:41 UTC, AmoabaKelvin commented on src/components/forms/dashboard/links/csv-shorten.tsx
> +      if (file.type === "text/csv") {
Can we show an error toast if the filetype is not a CSV?

`toast.error("Please upload a CSV file")`

2024-04-01 07:41 UTC, AmoabaKelvin commented on src/components/forms/dashboard/links/link-edit-form.tsx
Let's remove the commented out codes for the CSV functionality from this file.

2024-04-01 12:15 UTC, BreakTos commented
Completed the above tasks, No idea why prettier check is failing for those 2 documents. I formatted the code with Prettier extension before committing.

2024-04-15 06:12 UTC, closed without merging